<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Add to Wishlist_product-one-thumb</name>
   <tag></tag>
   <elementGuidId>e1221513-da42-4130-b1a3-afb9c79a10c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.noo-product-item.one.noo-product-sm-4.not_featured.post-1213.product.type-product.status-publish.has-post-thumbnail.product_cat-dress.product_cat-midi-dresses.product_tag-dress.product_tag-midi.product_tag-women.has-featured.instock.shipping-taxable.purchasable.product-type-variable > div.noo-product-inner > div.noo-product-thumbnail > div.noo-product-slider.owl-carousel.owl-theme > div.owl-wrapper-outer.autoHeight > div.owl-wrapper > div.owl-item.active > a.hover-device > img.product-one-thumb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4f6fe627-1445-40a5-859b-e2feb0d54444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>eaee5907-ca78-4f5a-a511-a4054d239322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>735cd967-9ce7-41a8-95df-6af87e3a0b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://shop.demoqa.com/wp-content/uploads/2019/04/black-strappy-polka-dot-ruched-midi-dress-300x300.jpg</value>
      <webElementGuid>6a6481c7-446b-4b9d-b7cb-ed3e56a4e20e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-one-thumb</value>
      <webElementGuid>a5477530-e613-4390-96af-067047b2b658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>74102911-65ec-42f5-8d3b-a202f5ec304a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>bc01f4b3-c9c8-4f64-86ba-a2464613a3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://shop.demoqa.com/wp-content/uploads/2019/04/black-strappy-polka-dot-ruched-midi-dress-300x300.jpg 300w, https://shop.demoqa.com/wp-content/uploads/2019/04/black-strappy-polka-dot-ruched-midi-dress-150x150.jpg 150w, https://shop.demoqa.com/wp-content/uploads/2019/04/black-strappy-polka-dot-ruched-midi-dress-650x650.jpg 650w, https://shop.demoqa.com/wp-content/uploads/2019/04/black-strappy-polka-dot-ruched-midi-dress-100x100.jpg 100w</value>
      <webElementGuid>d00af981-4b55-4a83-abdc-e11bc3b200e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>e47a2cc1-dd19-4ed8-bb29-d7d5a84930b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noo-site&quot;)/div[@class=&quot;noo-container-shop noo-shop-wrap&quot;]/div[@class=&quot;noo-row&quot;]/div[@class=&quot;noo-md-12 one&quot;]/div[@class=&quot;products noo-row&quot;]/div[@class=&quot;noo-product-item one noo-product-sm-4 not_featured post-1213 product type-product status-publish has-post-thumbnail product_cat-dress product_cat-midi-dresses product_tag-dress product_tag-midi product_tag-women has-featured  instock shipping-taxable purchasable product-type-variable&quot;]/div[@class=&quot;noo-product-inner&quot;]/div[@class=&quot;noo-product-thumbnail&quot;]/div[@class=&quot;noo-product-slider owl-carousel owl-theme&quot;]/div[@class=&quot;owl-wrapper-outer autoHeight&quot;]/div[@class=&quot;owl-wrapper&quot;]/div[@class=&quot;owl-item active&quot;]/a[@class=&quot;hover-device&quot;]/img[@class=&quot;product-one-thumb&quot;]</value>
      <webElementGuid>f5e17da4-ae60-4f98-a4af-0cacd0e0bc98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='noo-site']/div[2]/div[2]/div/div/div[11]/div/div/div[2]/div/div/div/a/img</value>
      <webElementGuid>0c2312d9-b997-4e4f-8c88-e3b7a81ec7b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://shop.demoqa.com/wp-content/uploads/2019/04/black-strappy-polka-dot-ruched-midi-dress-300x300.jpg')]</value>
      <webElementGuid>f3b11b04-296e-441c-a2bb-771e158238cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div[2]/div/div/div/a/img</value>
      <webElementGuid>87c5ff54-9ef3-4ae6-9a10-00e421ab79de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://shop.demoqa.com/wp-content/uploads/2019/04/black-strappy-polka-dot-ruched-midi-dress-300x300.jpg']</value>
      <webElementGuid>9346d2a4-5567-42da-9dcb-d52a637fffa9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
